name: Publish Python to PyPI if RELEASE

on: 
  create:  # on creation of tag
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Install build dependencies
        run: pip install wheel build

      - name: Build release artifacts
        run: python -m build
        
      - name: Publish package to PyPI
        if: contains(github.ref, 'RELEASE')  # check if tag contains 'RELEASE'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
