name: Build documentation

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-20.04
    strategy:
      # Make sure we never build docs in parallel in case we deploy new
      # versions to avoid potential race conditions while pushing to gh pages.
      max-parallel: 1
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          python -m pip install --upgrade pip
          pip install Sphinx
          pip install nbsphinx
          pip install sphinx_rtd_theme
          pip install sphinxcontrib-katex
          pip install myst-parser

      - name: Run doctests
        run: sphinx-build -b doctest docs $(mktemp -d)

      - name: Build docs
        run: |
          sphinx-build \
            -b html \
            docs \
            website/docs

      - name: Publish documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DOCUMENTATION_DEPLOY_KEY }}
          external_repository: CausalDisco/CausalDisco.docs
          publish_branch: main
          publish_dir: website/docs
          destination_dir: ./  # root dir in target repo
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: ${{ github.event.head_commit.message }}